version: '3'
services:
  redis:
    image: redis:latest
    container_name: grand2020-redis
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/grand2020redis:/data
  app:
    depends_on:
      - redis
    build: .
    container_name: grand2020-app
    command: npm start
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
